name: Publish Docker image

on:
  push:
    branches:
      - master
      - dev
      - dev2

jobs:
  push_to_docker_hub:
    name: ${{ matrix.docker_image}} (${{ matrix.arch }}) - build and push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu-14.04
            arch: linux/amd64
          - docker_image: manylinux2014_aarch64
            arch: linux/arm64
          - docker_image: manylinux_2_28_x86_64
            arch: linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/dockers/${{ matrix.docker_image }}/
          push: false
          platforms: ${{ matrix.arch }}
          tags: test
